#!/bin/sh
update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/garcon-url-handler 200
update-alternatives --install /usr/bin/www-browser www-browser /usr/bin/garcon-url-handler 200
