#!/bin/sh
set -e

rm -f /etc/systemd/user/default.target.wants/sommelier@0.service
rm -f /etc/systemd/user/default.target.wants/sommelier@1.service
rm -f /etc/systemd/user/default.target.wants/sommelier-x@0.service
rm -f /etc/systemd/user/default.target.wants/sommelier-x@1.service
update-alternatives --remove sommelier /opt/google/cros-containers/bin/sommelier
