#!/bin/sh
rm -f /etc/systemd/user/default.target.wants/sommelier@0.service
rm -f /etc/systemd/user/default.target.wants/sommelier@1.service
rm -f /etc/systemd/user/default.target.wants/sommelier-x@0.service
rm -f /etc/systemd/user/default.target.wants/sommelier-x@1.service
update-alternatives --remove sommelier /opt/google/cros-containers/bin/sommelier

# TODO(crbug.com/835959): Remove this once we fix mesa.
update-alternatives --remove swrast_dri /opt/google/cros-containers/lib/swrast_dri.so
